add install routine

diff --git a/lib/fobDetection b/lib/fobDetection
--- a/lib/fobDetection
+++ b/lib/fobDetection
@@ -22,14 +22,64 @@ if $localTest &&  ! $friendsOfBashLibFound && [ -d "$friendsOfBashPathLocal"  ] 
      friendsOfBashInclude="$friendsOfBashIncludeLocal"
 fi
 
-# script include: no friends of bash library detected
+# script include mode: no friends of bash library detected → stop here
 if ! $friendsOfBashLibFound && [ -z $INSTALLATION ]; then
     echo "No friends of bash library found."
     exit
 fi
 
-# script include: friends of bash library detected
-if $friendsOfBashLibFound && [ -z $INSTALLATION ]; then
-    source "$friendsOfBashInclude"
+# installation mode: the friends of bash library was not found
+if ! $friendsOfBashLibFound && [ ! -z $INSTALLATION ]; then
+    if $GLOBAL_INSTALLATION; then
+           friendsOfBashPath="$friendsOfBashPathRemote"
+        friendsOfBashInclude="$friendsOfBashIncludeRemote"
+    else
+           friendsOfBashPath="$friendsOfBashPathLocal"
+        friendsOfBashInclude="$friendsOfBashIncludeLocal"
+    fi
+
+    # ask the user
+    while true; do
+        read -p "Try to install the friends of bash library to \"$friendsOfBashPath\". Type (y)es or (n)o: " -n 1 yn
+        echo
+        case $yn in
+            [Yy]* ) result=$(git clone "$friendsOfBashGitUri" "$friendsOfBashPath" 2>&1); break;;
+            [Nn]* ) exit;;
+            * ) echo "Please answer yes or no.";;
+        esac
+    done
+
+    # git status is wrong
+    if [ $? -ne 0 ]; then
+        echo "Error occurred while installing the friends of bash library. The git was executed with status $?."
+        echo "$result"
+        exit 1
+    fi
+
+    # the fob folder was not found
+    if [ ! -d "$friendsOfBashPath" ]; then
+        echo "Error occurred while installing the friends of bash library. The folder \"$friendsOfBashPath\" was not found."
+        echo "$result"
+        exit 1
+    fi
+
+    # the include file was not found
+    if [ ! -f "$friendsOfBashInclude"  ]; then
+        echo "Error occurred while installing the friends of bash library. The include file \"$friendsOfBashInclude\" was not found."
+        echo "$result"
+        exit 1
+    fi
+
+    # everything is fine
+    friendsOfBashLibFound=true
 fi
+
+# script include: friends of bash library detected
+if ! $friendsOfBashLibFound; then
+    echo "Something went wrong while including the friends of bash library."
+    exit 1
+fi
+
+# include the friends of bash library
+source "$friendsOfBashInclude"
 
